### ISSUE TITLE
Can't install plugin on redmine 2.3

### ISSUE THREAD

**Issue by de1ayer** [Enkil/redmine_reminder#9]
root@intredmine:/usr/share/redmine# cat /etc/issue
Debian GNU/Linux jessie/sid
root@intredmine:/usr/share/redmine# apt-cache policy redmine
redmine:
  Installed: 2.3.1-1

When I try to install plugin after successful 'git clone' operation I receive following messages:

root@intredmine:/usr/share/redmine#rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
undefined method `asset_path' for #<Rails::Application::Configuration:0x96c8dfc>
/var/lib/gems/1.9.1/gems/railties-4.0.0/lib/rails/railtie/configuration.rb:95:in`method_missing'
/var/lib/gems/1.9.1/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-4.0.0/lib/rails/initializable.rb:30:in`run'
/var/lib/gems/1.9.1/gems/railties-4.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.0.0/lib/rails/initializable.rb:54:in`run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.0.0/lib/rails/application.rb:215:in `initialize!'
/var/lib/gems/1.9.1/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in`method_missing'
/var/lib/gems/1.9.1/gems/railties-4.0.0/lib/rails/application.rb:189:in `require'
/var/lib/gems/1.9.1/gems/railties-4.0.0/lib/rails/application.rb:189:in`require_environment!'
/var/lib/gems/1.9.1/gems/railties-4.0.0/lib/rails/application.rb:249:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

All needing gems are installed: shoulda-matchers (2.3.0) and factory_girl_rails (4.2.1)

**Comment by cforce** [comment]
Does it work on redmine 2.3.3?

**Comment by Enkil** [comment]
in my clear redmine install - yes
and also all good in clear redmine install on my clients servers
